version: '3.4'

services:
  tarefas.api:
    image: ${DOCKER_REGISTRY-}tarefasapi
    build:
      context: .
      dockerfile: src/Tarefas.Api/Dockerfile
    ports:
        - "8080:80"
    depends_on:
        - db

  db:
     image: "mcr.microsoft.com/mssql/server:2022-latest"
     ports:
         - "1433:1433"

     environment:
           SA_PASSWORD: "S3cur3P@ssW0rd!"
           ACCEPT_EULA: "Y"